# Generated by Django 5.1.1 on 2024-10-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='timecomplete',
        ),
    ]
