# Generated by Django 5.1.1 on 2024-10-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='complete',
        ),
    ]
