# Generated by Django 5.1.1 on 2024-10-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
    ]
